### ISSUE TITLE
Staff Application

### ISSUE THREAD

**Issue by ProfessorPiplup** [PrideCraft/Public-Issue-Tracker#11]
**Username:**
Please include your Minecraft username, Discord username, Tag, and ID ([don't know how to get your id?](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-))
LegitGamer1234, ポッチャマ教授
#3352,732363039528976494

**Why I want to be a staff member:**
Please include a short statement about why being staff appeals to you.
To help if needed

**Skill-set:**
Please include any skills you have that would make you a desirable asset.
I know a lot about Minecraft, I am learning how to code, and I am good and problem solving quickly

**Required skills**
It is required you check all the below.
- [x] I am willing to learn how to use GitHub.
- [x] I am willing to spend time learning the required Minecraft commands.
- [x] I am familiar with at least the basics of LGBT, and its community.
- [x] I understand that I will be held to a higher standard than normal users. Punishments for infractions will be far more severe than if I were a regular user.

**Desirable skills:**
Check all that applies, These are optional, you are not expected to have these skills.
- [ ] Familiar with Git
- [ ] Familiar with GitHub
- [ ] Previous staff experience
- [ ] Programming (I am Learning)

**Availability:**
Please state your schedule.
All week at noon

**Comment by Notarin** [comment]
Hey @ProfessorPiplup , There were some formatting issues with your application, I went ahead and fixed them

**Comment by CoolPanda101** [comment]
Thank you for your application we will keep it on file. We are currently not looking for staff members.

**Comment by Notarin** [comment]
@ProfessorPiplup If you wish to be seen as a higher quality candidate, please learn about git tracking, watch videos, make repos, make sure to demonstrate your ability.
