### ISSUE TITLE
Staff applications channel empty

### ISSUE THREAD

**Issue by ProfessorPiplup** [PrideCraft/Public-Issue-Tracker#12]
**Describe the bug**
The channel #staff-applications is empty
**To Reproduce**
1. Go to the Pridecraft discord server
2. Click on #staff-application

**Expected behavior**
I expected the channel to have staff applications

**Username**
Please include your Minecraft username, Discord username, Tag, and ID ([don't know how to get your id?](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-))
LegitGamer1234, ポッチャマ教授#3352, 732363039528976494

**Comment by CoolPanda101** [comment]
fixed
