### ISSUE TITLE
Toggle for riding entities

### ISSUE THREAD

**Issue by ProfessorPiplup** [PrideCraft/Public-Issue-Tracker#13]
**Feature Request**
Describe your suggestion.
I want a command to toggle riding entities
**Describe alternatives you've considered**
A command to toggle riding entities
**Username**
Please include your Minecraft username, Discord username, Tag, and ID ([don't know how to get your id?](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-))
LegitGamer1234, ポッチャマ教授#3352, 732363039528976494

**Comment by Notarin** [comment]
made https://github.com/PrideCraft/Mobrider

**Comment by Notarin** [comment]
waiting to see result on server reboot

**Comment by Notarin** [comment]
fixed with 92a1736f852f4d59cd39b63f18f45cea0d97d698

**Comment by Notarin** [comment]
fixed with PrideCraft/Mobrider@92a1736f852f4d59cd39b63f18f45cea0d97d698
