### ISSUE TITLE
Items and entities gets missing in the end portal

### ISSUE THREAD

**Issue by basil222** [PrideCraft/Public-Issue-Tracker#14]
Portal in the end will not bring any item or entity to the over world.

The portal in the end dimension will bring player to spawn but not item or entity, for now any item or entity entering the portal gets missing.

Expected behaver will be to bring the item or entities to spawn

-MC: Basil_LMC   Discord: Basil#8003

**Comment by Notarin** [comment]
I would not even begin to know how to debug this.
I will take a look at it, but have no hopes for it, closing as not planned, if I manage to get an idea on what to do about this I'll reopen this
