### ISSUE TITLE
Text customization

### ISSUE THREAD

**Issue by basil222** [PrideCraft/Public-Issue-Tracker#15]
I think text customization on renaming items and in signs would be grate,
Like being able to change the color and the different formats like obfuscated, bold, strikethrough, underline, italic, reset, ect...

-MC: Basil_LMC  Discord: Basil#8003

**Comment by GhostOfTheSynthesis** [comment]
correct me if i'm wrong but i believe we already have this feature for some of our paid ranks! /irename comes with either emerald or diamond and /ilore comes with tourmaline :)
if you have access to these commands and wish to utilize them, just hold the item you want to rename and do /irename <name>. you can add color codes this way too!
i wanna talk to Panda about ranks and what they have. maybe i could bring this up to him too :]

**Comment by CoolPanda101** [comment]
Before you had to be a diamond rank to access irename i have changed this to Amethyst not a bug
