### ISSUE TITLE
/nick isn't working for people with emerald rank

### ISSUE THREAD

**Issue by ProfessorPiplup** [PrideCraft/Public-Issue-Tracker#16]
**Describe the bug**
/nick isn't working for KreW (an emerald)
**To Reproduce**
1. Go to the Pridecraft server
2. Type "/nick hi
4. See "You do not have access to that command"

**Expected behavior**
To change what your name looks like
**Screenshots**
Cannot
**Username**
Please include your Minecraft username, Discord username, Tag, and ID ([don't know how to get your id?](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-))
LegitGamer1234, ポッチャマ教授#3352, 732363039528976494

**Comment by GhostOfTheSynthesis** [comment]
So sorry about this! We'll be sure to get this fixed as soon as possible :)
List of ranks that should be able to access /nick
 **Vote ranks**
- [ ] - Iconic
- [ ] - Veteran
 **Paid ranks**
- [ ] - Sapphire
- [ ] - Ruby
- [ ] - Amethyst
- [ ] - Emerald
- [ ] - Diamond
- [ ] - Tourmaline
 **Booster Ranks**
- [ ] - Booster
- [ ] - Ultra Booster
I am assigning this to Panda as he's the only one that can work with permissions right now.

**Comment by CoolPanda101** [comment]
Nick is now a Amethyst+ rank and instead Sapphire has been given /pweather

**Comment by Notarin** [comment]
> Nick is now a Amethyst+ rank and instead Sapphire has been given /pweather 

Do we have any plans to grandfather members who have already had those roles?
It seems unfair for us to take away something they already had, Even worse so when they actually paid for it.
Excuse me if I'm misunderstanding something.

**Comment by CoolPanda101** [comment]
fixed

**Comment by Notarin** [comment]
> List of ranks that should be able to access /nick
@GhostOfTheSynthesis 
Is this supposed to be a list or completely unchecked checklist?

**Comment by Notarin** [comment]
> fixed

By fix do you mean won't fix? Or do you mean that you've reverted changes?

**Comment by GhostOfTheSynthesis** [comment]
@Notarin the idea was to check every rank once it was given the permission.

**Comment by CoolPanda101** [comment]
Amethyst+ gets nick
