### ISSUE TITLE
/irename command not working

### ISSUE THREAD

**Issue by DragomiAJ** [PrideCraft/Public-Issue-Tracker#18]
**Describe the bug**

Despite being donor rank Diamond I have no access to the /irename command. It shows as red for me and when I hit enter it says I do not have access to the command.

**To Reproduce**
1. Type /irename while being diamond rank only
2. Hit enter

**Expected behavior**
Should have renamed the item to the desired text.

**Username**
Please include your Minecraft username, Discord username, Tag, and ID ([don't know how to get your id?](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)) 
DragomiAJ, Drag#8763, ID: 496540341764358144

**Comment by ProfessorPiplup** [comment]
It seems a lot of the donor commands aren't working properly

**Comment by Notarin** [comment]
@CoolPanda101

**Comment by CoolPanda101** [comment]
@DragomiAJ you can now use
/rename
 /lore
 /setloreline
/removeloreline
/insertloreline
/glow
 /removeglow
 /removename
 /removelore
