### ISSUE TITLE
Staff Application - Apricot.Beetle#1010

### ISSUE THREAD

**Issue by Doogster** [PrideCraft/Public-Issue-Tracker#19]
**Username:**
MC User: Kinq_Atlas
Discord: Apricot.Beetle#1010
ID: 521502006909599744

**Why I want to be a staff member:**
I wish to be a staff member because I care a lot about the players on the server. I've playing on PrideCraft for quite a while now and everyone has been incredibly kind; I'd like to give back and help make the server a welcoming and kind place for the future player base as well.

**Skill-set:**
For starters I have a bit of knowledge about how servers run and some experience moderating mid-sized discord servers as well. I feel as if I have a good understanding of Minecraft commands and I keep an open mind when it comes to things I don't understand. I can adapt to what calls of me due to the fact I'm a fast learner as well.

**Required skills**
It is required you check all the below.
- [X] I am willing to learn how to use GitHub.
- [X] I am willing to spend time learning the required Minecraft commands.
- [X] I am familiar with at least the basics of LGBT, and it's community.
- [X] I understand that I will be held to a higher standard than normal users. Punishments for infractions will be far more severe than if I were a regular user.

**Desirable skills:**
Check all that applies, These are optional, you are not expected to have these skills.
- [ ] Familiar with Git
- [ ] Familiar with GitHub
- [ ] Previous staff experience
- [ ] Programming

**Availability:**
I can hop on the MC server almost everyday, I go by PST so the only time I 100% cannot be on the server is Mondays at 11AM-11:50PM. I have online school so I can help out on the Discord server basically all day.

**Comment by Notarin** [comment]
Thank you for your application, at this moment in time we are not accepting applications.
However, your application will be archived for future use and will be reviewed before incoming applications in the future.
We will let you know if you application is denied, thank you.
Consider your application on hiatus.

**Comment by CoolPanda101** [comment]
application denied user hasnt been online for 23 days
