### ISSUE TITLE
GrayRayne

### ISSUE THREAD

**Issue by GrayRayne** [PrideCraft/Public-Issue-Tracker#20]
**Username:**
Please include your Minecraft username, Discord username, Tag, and ID ([don't know how to get your id?](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-))<br>
(Replace this text)

**Why I want to be a staff member:**
Please include a short statement about why being staff appeals to you.<br>
(Replace this text)

**Skill-set:**
Please include any skills you have that would make you a desirable asset.<br>
(Replace this text)

**Required skills**
It is required you check all the below. [Don't know how?](https://www.markdownguide.org/extended-syntax/#task-lists)
- [ ] I am willing to learn how to use GitHub.
- [ ] I am willing to spend time learning the required Minecraft commands.
- [ ] I am familiar with at least the basics of LGBT, and it's community.
- [ ] I understand that I will be held to a higher standard than normal users. Punishments for infractions will be far more severe than if I were a regular user.

**Desirable skills:**
Check all that applies, These are optional, you are not expected to have these skills.
- [ ] Familiar with Git
- [ ] Familiar with GitHub
- [ ] Previous staff experience
- [ ] Programming

**Availability:**
Please state your schedule.<br>
(Replace this text)

**Comment by Notarin** [comment]
Hello, thank you for your application, unfortunately you have not checked the minimum requirements in order to apply for staff.
until you meet these requirements you application will not be considered.
