### ISSUE TITLE
/back dosn't function as expected when executed after plot visit command

### ISSUE THREAD

**Issue by basil222** [PrideCraft/Public-Issue-Tracker#21]
**Describe the bug**
A clear and concise description of what the bug is:<br>
when used /back after using /plot visit, /back will not bring you back to where you stranded just before doing plot visit command but back to where you standed one tp back. ex: if you visited my base and then spawn, and then did /plot visit and did /back just after, you dould not be back to spawn but back to my base.

**To Reproduce**
Steps to reproduce the behavior: (remove unused steps please)
1. go to point A
2. go to point B
3. do /plot visit Basil_LMC
4. do /back

**Expected behavior**
should bring back to point B, but brings back to point A

**Screenshots**

**Username**
Basil_LMC
Basil#8003

**Comment by Notarin** [comment]
this is impossible to fix without the developers of said plugins making serious changes to their apis, these plugins do not communicate with eachother, essentials has no way to know that "plots" has moved the player
