### ISSUE TITLE
/warp Farm no longer works after making spawn ungriefable

### ISSUE THREAD

**Issue by DragomiAJ** [PrideCraft/Public-Issue-Tracker#22]
**Describe the bug**
A clear and concise description of what the bug is:<br>
/warp farm no longer can be used. Crops cannot be broken and chests/smokers are unable to be used.

**To Reproduce**
Steps to reproduce the behavior: (remove unused steps please)
1. Go to /warp farm
2. Break crops 
3. Try to open chests/smokers

**Expected behavior**
A clear and concise description of what you expected to happen.<br>
The crops should break and you should be able to open the chests/smokers.

**Screenshots**
![2022-10-24_13 10 36](https://user-images.githubusercontent.com/115872812/197620199-0002f082-0dbe-4bd9-8773-87dac4638a1d.png)
![2022-10-24_13 10 28](https://user-images.githubusercontent.com/115872812/197620356-40cbba22-e169-427a-a6b0-2da7133f4b12.png)

**Username**
Please include your Minecraft username, Discord username, Tag, and ID ([don't know how to get your id?](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-))<br>
(Replace this text) DragomiAJ, Drag#8763, 496540341764358144

**Comment by GhostOfTheSynthesis** [comment]
this has been fixed for a while now, don't know why nobody closed it
