### ISSUE TITLE
November Crate Ideas

### ISSUE THREAD

**Issue by GhostOfTheSynthesis** [PrideCraft/Public-Issue-Tracker#23]
Now that we're nearing November, we need ideas for a new monthly crate! If you have any ideas, please leave them below :)

**Comment by ProfessorPiplup** [comment]
Obviously turkey that gives you a bunch of buffs but it also guves you slowness because it's a lot of food, oh yeah it also fills your health to the max

**Comment by Notarin** [comment]
> Obviously turkey that gives you a bunch of buffs but it also guves you slowness because it's a lot of food, oh yeah it also fills your health to the max

Not sure how to make it refill health, as far as I can tell this is not possible without coding a custom plugin.
However, It can give max saturation which should heal a significant amount.
This also makes perfect sense too.

**Comment by DragomiAJ** [comment]
Maybe a shulker box filled with some food items and call it The Cornucopia. since thats like a big fall/thanksgiving thing

**Comment by CoolPanda101** [comment]
We will not do a November crate but we will do a chrimstas one
