### ISSUE TITLE
Shulker goes missing

### ISSUE THREAD

**Issue by v-ncentt** [PrideCraft/Public-Issue-Tracker#27]
**Describe the bug**
My shulker disapeared. I turned around and POOF!

**To Reproduce**
N/A

**Expected behavior**
It wouldn't disappear...

**Screenshots**

https://user-images.githubusercontent.com/117108927/199071318-ef5dee7c-4b6a-4d39-b76e-04c085ecdf54.mp4

**Username**
Please include your Minecraft username, Discord username, Tag, and ID
MC: Poseter DU: theo<3.#8977

**Comment by Notarin** [comment]
@v-ncentt can you provide coordinates of the event?

**Comment by GhostOfTheSynthesis** [comment]
![image](https://user-images.githubusercontent.com/114524109/199152028-70f194cd-55fa-4bd1-b2fd-63352e76540a.png)
Core Protect shows that the shulker box was placed and clicked, but not broken. Looking closely at the subtitles of the video, the shulker box was clearly broken. 
![image](https://user-images.githubusercontent.com/114524109/199152085-5a780721-45b5-4625-9b0c-313c575c617e.png)
Core Protect command was only limited by block and not user. It's not possible for someone else to have broken it.

**Comment by Notarin** [comment]
Interesting

**Comment by Notarin** [comment]
I'm at work

**Comment by Notarin** [comment]
Just run the same command but replace l with restore

**Comment by ProfessorPiplup** [comment]
Ok

**Comment by Notarin** [comment]
restore command worked as expected, closing as solved
