### ISSUE TITLE
Vote Crate

### ISSUE THREAD

**Issue by honeydewhq** [PrideCraft/Public-Issue-Tracker#28]
**Feature Request**
Describe your suggestion:<br>
Remove the end crystals from the vote crate since we cant spawn the dragon anymore they're pretty useless.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered:<br>
The end crystals could be replaced with dragons breath since there's no way to get it now.

**Username**
Please include your Minecraft username, Discord username, Tag, and ID ([don't know how to get your id?](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-))<br>
honeydewhq,  honeydewhq#3239, 675124212553220111

**Comment by CoolPanda101** [comment]
@Notarin your job

**Comment by GhostOfTheSynthesis** [comment]
done! :) ![image](https://user-images.githubusercontent.com/114524109/204199708-61384a7a-1f98-489f-8dce-9e2511726163.png)
