### ISSUE TITLE
Staff Application

### ISSUE THREAD

**Issue by honeydewhq** [PrideCraft/Public-Issue-Tracker#30]
**Username:**
Please include your Minecraft username, Discord username, Tag, and ID ([don't know how to get your id?](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-))<br>
honeydewhq, honeydewhq#3239, 675124212553220111

**Why I want to be a staff member:**
Please include a short statement about why being staff appeals to you.<br>
I've been playing on this server for months and its very important to me so I'd like to be a part of improving it. I also enjoy helping people with anything that I can.

**Skill-set:**
Please include any skills you have that would make you a desirable asset.<br>
I am very familiar with the LGBT community.

**Required skills**
It is required you check all the below. [Don't know how?](https://www.markdownguide.org/extended-syntax/#task-lists)
- [x] I am willing to learn how to use GitHub.
- [x] I am willing to spend time learning the required Minecraft commands.
- [x] I am familiar with at least the basics of LGBT, and it's community.
- [x] I understand that I will be held to a higher standard than normal users. Punishments for infractions will be far more severe than if I were a regular user.

**Desirable skills:**
Check all that applies, These are optional, you are not expected to have these skills.
- [ ] Familiar with Git
- [ ] Familiar with GitHub
- [ ] Previous staff experience
- [ ] Programming

**Availability:**
Please state your schedule.<br>
12pm-4pm and 9pm-12am cst

**Comment by CoolPanda101** [comment]
I want to welcome you to the staff team. Although more information would have usually been necessary because of your experience in the LGBTQ community and playing for months that's the kind of experience we need.

ACCEPTED.
