### ISSUE TITLE
Staff application 

### ISSUE THREAD

**Issue by ProfessorPiplup** [PrideCraft/Public-Issue-Tracker#31]
**Username:**
Please include your Minecraft username, Discord username, Tag, and ID ([don't know how to get your id?](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-))<br>
LegitGamer1234, ProfessorPiplup#3352, 732363039528976494

**Why I want to be a staff member:**
Please include a short statement about why being staff appeals to you.<br>
So people won't hesitate to ask for help

**Skill-set:**
Please include any skills you have that would make you a desirable asset.<br>
I help a lot and know a lot about minecraft and this server

**Required skills**
It is required you check all the below. [Don't know how?](https://www.markdownguide.org/extended-syntax/#task-lists)
- [x] I am willing to learn how to use GitHub.
- [x] I am willing to spend time learning the required Minecraft commands.
- [x] I am familiar with at least the basics of LGBT, and it's community.
- [x] I understand that I will be held to a higher standard than normal users. Punishments for infractions will be far more severe than if I were a regular user.

**Desirable skills:**
Check all that applies, These are optional, you are not expected to have these skills.
- [ ] Familiar with Git
- [ ] Familiar with GitHub
- [ ] Previous staff experience
- [ ] Programming <learning>

**Availability:**
Please state your schedule.<br>
Everyday 12 pm to 12 am GMT

**Comment by CoolPanda101** [comment]
Application denied. We would like to see more information. You may re apply in 30 days

**Comment by Notarin** [comment]
@ProfessorPiplup heads up, in the future, don't duplicate you application, instead, reopen your old application
