### ISSUE TITLE
application :]

### ISSUE THREAD

**Issue by VoyenFG** [PrideCraft/Public-Issue-Tracker#32]
**Username:**
Please include your Minecraft username, Discord username, Tag, and ID ([don't know how to get your id?](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-))<br>
_(Discord: Voyen#2334 Dc ID: 722438468684480564   Mc username: Voyen_ )_

**Why I want to be a staff member:**
Please include a short statement about why being staff appeals to you.<br>
_(because i wanna keep stuff in order and help others have fun with as little issues as possible)_
**Skill-set:**
Please include any skills you have that would make you a desirable asset.<br>
_(gaslighting and emotional manipulation)_
**Required skills**
It is required you check all the below. [Don't know how?](https://www.markdownguide.org/extended-syntax/#task-lists)
- [x] I am willing to learn how to use GitHub.
- [x] I am willing to spend time learning the required Minecraft commands.
- [x] I am familiar with at least the basics of LGBT, and it's community.
- [ ] I understand that I will be held to a higher standard than normal users. Punishments for infractions will be far more severe than if I were a regular user.

**Desirable skills:**
Check all that applies, These are optional, you are not expected to have these skills.
- [ ] Familiar with Git
- [ ] Familiar with GitHub
- [x] Previous staff experience
- [ ] Programming

**Availability:**
Please state your schedule.<br>
_(from 14:25 ,16:15 CET to 21:00 , 22:00 CET)_

**Comment by ProfessorPiplup** [comment]
Please say your skillset is a joke

**Comment by CoolPanda101** [comment]
Application denied. Didn't agree to all required skills i.e hold to a higher standard. Not enough information in the application. Questionable skill set. You may re-apply in 30 days. Next time put some more effort in
