### ISSUE TITLE
The entire server is gone.  

### ISSUE THREAD

**Issue by RedTekk8** [PrideCraft/Public-Issue-Tracker#34]
**Describe the bug**
A clear and concise description of what the bug is:<br>

The entire server is gone.  Minecraft and discord, everything is gone and it appears that the owner of the server has blocked several members of old staff.  

**To Reproduce**
Steps to reproduce the behavior: (remove unused steps please)

Open discord or Minecraft and try to connect.  

**Expected behavior**
A clear and concise description of what you expected to happen.<br>

Should be able to connect to the server, or at least get some information about why this is happening

**Username**
Please include your Minecraft username, Discord username, Tag, and ID ([don't know how to get your id?](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-))<br>
Minecraft: RedTekk8
Discord: RedTekk8#4599 / 168420839446937600

**Comment by basil222** [comment]
damn

**Comment by GhostOfTheSynthesis** [comment]
this has been fixed! although we have a lot of issues that we need to fix, the server's up and playable :)
