### ISSUE TITLE
Some bugs i found from server change

### ISSUE THREAD

**Issue by basil222** [PrideCraft/Public-Issue-Tracker#35]
**Describe the bug**
A clear and concise description of what the bug is:<br>
The sit plugin doesn't work (/sit),
player tab,
chat(wirld stuff in player name and message),
pronouns plugin doesn't work,
/msg doesn't work,

**To Reproduce**
Steps to reproduce the behavior: (remove unused steps please)
test stuff I mentioned!

**Expected behavior**
should work!

**Screenshots**

**Username**
Please include your Minecraft username, Discord username, Tag, and ID ([don't know how to get your id?](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-))<br>
(Basil_LMC Basil#8003)

**Comment by Notarin** [comment]
Please turn these problems into their each own individual issues
