### ISSUE TITLE
Mob ride resets after rejoining

### ISSUE THREAD

**Issue by RedTekk8** [PrideCraft/Public-Issue-Tracker#41]
**Describe the bug**
A clear and concise description of what the bug is:<br>
If you turn off mob riding by running either the ./togglemobriding or the ./tglmr command then rejoin, it resets the toggle to turn back on mob riding.  This can be very annoying when clicking on a mob/minecart/itemframe and instead of interacting it makes you ride the entity.  

**To Reproduce**
Steps to reproduce the behavior: (remove unused steps please)
1. Ride a mob (to prove that the toggle is on)
2. Run ./tglmr
3. Try to ride a mob (to prove that the toggle is off)
4. Rejoin the server
5. Ride a mob again (Its back on)

**Expected behavior**
A clear and concise description of what you expected to happen.<br>
It would be far nicer to have it either default to off, or remember what the player had it last toggled to.  

**Username**
Please include your Minecraft username, Discord username, Tag, and ID ([don't know how to get your id?]
Minecraft: RedTekk8
Discord: RedTekk8#4599 / 168420839446937600

**Comment by GhostOfTheSynthesis** [comment]
This is intentional but we can see what Notarin has to say about it

**Comment by RedTekk8** [comment]
Edit:  toggle only resets when the server resets, which is at least daily.  This still allows for players to forget to turn it off and accidently break something.  I think if a player turns off mob riding, it should stay off for that player until they decide to turn it back on.

**Comment by Notarin** [comment]
This is the wrong repository to report this
https://github.com/PrideCraft/Mobrider
