### ISSUE TITLE
Basil's application 

### ISSUE THREAD

**Issue by basil222** [PrideCraft/Public-Issue-Tracker#43]
**Username:**
Basil_LMC Basil#8003

**Why I want to be a staff member:**
To help the PrideCraft community. 

**Skill-set:**
Video editor, I got some experience in video editing from some personal projects, I also had some experience in Minecraft replay mod

**Required skills**
- [x] I am willing to learn how to use GitHub.
- [x] I am willing to spend time learning the required Minecraft commands.
- [x] I am familiar with at least the basics of LGBT, and it's community.
- [x] I understand that I will be held to a higher standard than normal users. Punishments for infractions will be far more severe than if I were a regular user.

**Desirable skills:**
- [ ] Familiar with Git
- [x] Familiar with GitHub
- [ ] Previous staff experience
- [ ] Programming
- [x] Video editing

**Availability:**
I am mostly available in the weekends

**Comment by Notarin** [comment]
Hi @basil222 what video editors are you familiar with? and do you have any sort of portfolio or evident experience?

**Comment by Notarin** [comment]
@basil222 Would you be comfortable learning a new editor? KDenlive for example?

**Comment by basil222** [comment]
Yes

**Comment by Notarin** [comment]
@basil222 Welcome to the team!
