### ISSUE TITLE
RedTekk8's Application

### ISSUE THREAD

**Issue by RedTekk8** [PrideCraft/Public-Issue-Tracker#44]
**Username:**
Please include your Minecraft username, Discord username, Tag, and ID ([don't know how to get your id?]
Minecraft: RedTekk8
Discord: RedTekk8#4599 / 168420839446937600

**Why I want to be a staff member:**
Please include a short statement about why being staff appeals to you.<br>
Would be nice to learn more about server management and development.  

**Skill-set:**
Please include any skills you have that would make you a desirable asset.<br>
I already know and understand the basics of coding, and Im always looking to learn more.  

**Required skills**
It is required you check all the below. [Don't know how?](https://www.markdownguide.org/extended-syntax/#task-lists)
- [x] I am willing to learn how to use GitHub.
- [x] I am willing to spend time learning the required Minecraft commands.
- [x] I am familiar with at least the basics of LGBT, and it's community.
- [x] I understand that I will be held to a higher standard than normal users. Punishments for infractions will be far more severe than if I were a regular user.

**Desirable skills:**
Check all that applies, These are optional, you are not expected to have these skills.
- [ ] Familiar with Git
- [ ] Familiar with GitHub
- [x] Previous staff experience
- [x] Programming
- [ ] Video editing

**Availability:**
Please state your schedule.<br>
A couple hours per week

**Comment by Notarin** [comment]
I've discussed this with @RedTekk8 , they're not sure on their application yet, so we're putting his application in stock, because they have no issues with their application and have a desirable skill-set

**Comment by RedTekk8** [comment]
re-open

**Comment by Notarin** [comment]
Approved, welcome to the team!
