### ISSUE TITLE
Doogster's Application

### ISSUE THREAD

**Issue by Doogster** [PrideCraft/Public-Issue-Tracker#46]
**Username:**
Kinq_Atlas
Apricot.Beetle#1010
521502006909599744

**Why I want to be a staff member:**
I want to help Pridecraft build back up and reach out to new players so we can have a larger community! :)

**Skill-set:**
I know how to use Camtasia editing software and Sony Vegas, I also help run profiles for a podcast that I have with other members from a different server. I can help the server advertise and also help moderate the servers.

**Required skills**
It is required you check all the below. [Don't know how?](https://www.markdownguide.org/extended-syntax/#task-lists)
- [x] I am willing to learn how to use GitHub.
- [x] I am willing to spend time learning the required Minecraft commands.
- [x] I am familiar with at least the basics of LGBT, and it's community.
- [x] I understand that I will be held to a higher standard than normal users. Punishments for infractions will be far more severe than if I were a regular user.

**Desirable skills:**
Check all that applies, These are optional, you are not expected to have these skills.
- [ ] Familiar with Git
- [ ] Familiar with GitHub
- [ ] Previous staff experience
- [ ] Programming
- [x] Video editing

**Availability:**
I'm mostly available around mid day as well as weekdays. I'm also free around the evenings. (All this is in regards to PST)

**Comment by Notarin** [comment]
@Doogster Would you be comfortable learning a new editor? KDenlive for example?

**Comment by Doogster** [comment]
> @Doogster Would you be comfortable learning a new editor? KDenlive for example?

I'd love to learn any new software <:D expanding my knowledge in video editing is a huge interest of mine!

**Comment by Notarin** [comment]
@Doogster Welcome to the team!
