### ISSUE TITLE
Vote channel in discord

### ISSUE THREAD

**Issue by MrTomat0o** [PrideCraft/Public-Issue-Tracker#48]
**Feature Request**
Describe your suggestion:<br>
Add a channel at the top of the server that displays all the voting sites for the server. Not everyone has the chance to hop on Minecraft, so I figured why not suggest that we add a channel where all the voting sites are. It’s practical and allows players to vote even when they’re not able to log on.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered:<br>
(Replace this text)

**Username**
Please include your Minecraft username, Discord username, Tag, and ID ([don't know how to get your id?](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-))<br>
Discord: MrTomat0o#4343
Minecraft: Mr_Tomat0o

**Comment by GhostOfTheSynthesis** [comment]
Our list of vote sites and links is now recorded [here](https://github.com/PrideCraft/Public-Issue-Tracker/blob/server-info/vote.md)! It will be in the discord momentarily. :)
