### ISSUE TITLE
/vanish bug

### ISSUE THREAD

**Issue by RedTekk8** [PrideCraft/Public-Issue-Tracker#50]
**Describe the bug**
A clear and concise description of what the bug is:<br>

> When a mod goes into /vanish, it does not generate a 'left the game' message.  This means that if someone was paying attention, they could see a moderator's name go away from the tab list, but not see the leave message.  Meaning that a player could potentially know when a mod is in vanish

**To Reproduce**
Steps to reproduce the behavior: (remove unused steps please)
> 1. Go into the server with an admin/mod (watch their join message)
> 2. Watch the tab list as the admin goes into /v
> 3. Observe the lack of 'left the game' message

**Expected behavior**
A clear and concise description of what you expected to happen.<br>
> In general, /v is suppose to make it look like the admin is not on the server.  That way the players wont think they are being watched.  /v should generate a 'left the game' message when activated and a 'joined the game' message when de-activated

**Username**
Please include your Minecraft username, Discord username, Tag, and ID ([don't know how to get your id?]Minecraft username: 

> RedTekk8
> Discord username: RedTekk8#4599 / 168420839446937600

**Comment by Notarin** [comment]
This is intended behavior, A mod going offline after doing hacks is suspicious.
Either way they may see the mods name disappear from the tab list, but without the leave message, they will have a harder time telling a mod is vanished.
